# SPDX-License-Identifier: GPL-2.0
# Core
obj-$(CONFIG_ARCH_MEDIATEK) += clk-mtk.o

# SoC Drivers
obj-$(CONFIG_MT8512) += clk-mt8512.o
obj-$(CONFIG_TARGET_MT7623) += clk-mt7623.o
obj-$(CONFIG_TARGET_MT7622) += clk-mt7622.o
obj-$(CONFIG_TARGET_MT7629) += clk-mt7629.o
obj-$(CONFIG_TARGET_MT8183) += clk-mt8183.o
obj-$(CONFIG_TARGET_MT8195) += clk-mt8195.o clk-mt8195-apmixedsys.o \
			       clk-mt8195-topckgen.o clk-mt8195-infra_ao.o
obj-$(CONFIG_TARGET_MT8365) += clk-mt8365.o
obj-$(CONFIG_TARGET_MT8516) += clk-mt8516.o
obj-$(CONFIG_TARGET_MT8518) += clk-mt8518.o
