# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2022 BayLibre, SAS
#
# Author: Julien Masson <jmasson@baylibre.com>

obj-$(CONFIG_VIDEO_MEDIATEK) += \
	mtk_ddp.o \
	mtk_dpi.o \
	mtk_disp_mutex.o \
	mtk_disp_rdma.o \
	mtk_smi.o
