/*
 * Copyright (C) 2013, Boundary Devices <info@boundarydevices.com>
 *
 * SPDX-License-Identifier:	GPL-2.0+
 */

#undef MX6PAD
#undef MX6NAME

#ifdef FOR_DL_SOLO
#define MX6PAD(a) MX6DL_PAD_##a
#define MX6NAME(a) mx6dl_solo_##a
#else
#define MX6PAD(a) MX6Q_PAD_##a
#define MX6NAME(a) mx6q_##a
#endif


#define AUD_PAD_CTRL  (PAD_CTL_PUS_100K_UP |			\
	PAD_CTL_SPEED_LOW | PAD_CTL_DSE_40ohm |			\
	PAD_CTL_HYS | PAD_CTL_SRE_FAST)

#define CSI_PAD_CTRL  (PAD_CTL_PUS_100K_UP |			\
	PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm |			\
	PAD_CTL_HYS | PAD_CTL_SRE_FAST)

#define UART_PAD_CTRL  (PAD_CTL_PUS_100K_UP |			\
	PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm |			\
	PAD_CTL_HYS | PAD_CTL_SRE_FAST)

#define USDHC_CLK_PAD_CTRL (PAD_CTL_SPEED_LOW | PAD_CTL_DSE_40ohm | \
	PAD_CTL_SRE_FAST  | PAD_CTL_HYS)

#define USDHC_PAD_CTRL (USDHC_CLK_PAD_CTRL | PAD_CTL_PUS_47K_UP)

#define ENET_PAD_CTRL  (PAD_CTL_PUS_100K_UP |			\
	PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm | PAD_CTL_HYS)

#define SPI_PAD_CTRL (PAD_CTL_HYS | PAD_CTL_SPEED_MED |		\
	PAD_CTL_DSE_40ohm     | PAD_CTL_SRE_FAST)

#define BUTTON_PAD_CTRL (PAD_CTL_PUS_100K_UP |			\
	PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm | PAD_CTL_HYS)

#define I2C_PAD_CTRL	(PAD_CTL_PUS_100K_UP |			\
	PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm | PAD_CTL_HYS |	\
	PAD_CTL_ODE | PAD_CTL_SRE_FAST)

#define WEAK_PULLUP	(PAD_CTL_PUS_100K_UP |			\
	PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm | PAD_CTL_HYS |	\
	PAD_CTL_SRE_SLOW)

#define WEAK_PULLUP_OUTPUT (PAD_CTL_PUS_100K_UP |		\
	PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm | PAD_CTL_SRE_SLOW)

#define WEAK_PULLDN	(PAD_CTL_PUS_100K_DOWN |		\
	PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm |			\
	PAD_CTL_HYS | PAD_CTL_SRE_SLOW)

#define WEAK_PULLDN_OUTPUT (PAD_CTL_PUS_100K_DOWN |		\
	PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm |	PAD_CTL_SRE_SLOW)

#define CEC_PAD_CTRL	(PAD_CTL_HYS | PAD_CTL_PUS_22K_UP | PAD_CTL_ODE | \
	PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm | PAD_CTL_SRE_FAST)

#define OUTPUT_40OHM (PAD_CTL_SPEED_MED|PAD_CTL_DSE_40ohm)

static const iomux_v3_cfg_t MX6NAME(insp_pads)[] = {
	/* HOG */
#define GP_MAIN_POWER_EN	IMX_GPIO_NR(3, 5)
	NEW_PAD_CTRL(MX6PAD(EIM_DA5__GPIO3_IO05), WEAK_PULLUP),
#define GP_MAIN_POWER_BUTTON	IMX_GPIO_NR(3, 6)
	NEW_PAD_CTRL(MX6PAD(EIM_DA6__GPIO3_IO06), WEAK_PULLUP),

	/* ADV7180 */
	/* camera - video0 - ADV7180 - I2C3, crystal 28.636 MHz */
	NEW_PAD_CTRL(MX6PAD(CSI0_DAT12__IPU1_CSI0_DATA12), CSI_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(CSI0_DAT13__IPU1_CSI0_DATA13), CSI_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(CSI0_DAT14__IPU1_CSI0_DATA14), CSI_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(CSI0_DAT15__IPU1_CSI0_DATA15), CSI_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(CSI0_DAT16__IPU1_CSI0_DATA16), CSI_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(CSI0_DAT17__IPU1_CSI0_DATA17), CSI_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(CSI0_DAT18__IPU1_CSI0_DATA18), CSI_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(CSI0_DAT19__IPU1_CSI0_DATA19), CSI_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(CSI0_PIXCLK__IPU1_CSI0_PIXCLK), CSI_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(CSI0_MCLK__GPIO5_IO19), WEAK_PULLUP),	/* Hsync */
	NEW_PAD_CTRL(MX6PAD(CSI0_VSYNC__GPIO5_IO21), WEAK_PULLUP),	/* Vsync */
#define GP_ADV7180_RESET	IMX_GPIO_NR(2, 25)
	NEW_PAD_CTRL(MX6PAD(EIM_OE__GPIO2_IO25), WEAK_PULLUP_OUTPUT),
#define GP_ADV7180_IRQ		IMX_GPIO_NR(2, 26)
	NEW_PAD_CTRL(MX6PAD(EIM_RW__GPIO2_IO26), WEAK_PULLUP),

	/* AUDMUX */
	NEW_PAD_CTRL(MX6PAD(CSI0_DAT7__AUD3_RXD), AUD_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(CSI0_DAT4__AUD3_TXC), AUD_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(CSI0_DAT5__AUD3_TXD), AUD_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(CSI0_DAT6__AUD3_TXFS), AUD_PAD_CTRL),

	/* ECSPI1 */
	NEW_PAD_CTRL(MX6PAD(EIM_D17__ECSPI1_MISO), SPI_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(EIM_D18__ECSPI1_MOSI), SPI_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(EIM_D16__ECSPI1_SCLK), SPI_PAD_CTRL),
#define GP_ECSPI1_CS1	IMX_GPIO_NR(3, 19)
	NEW_PAD_CTRL(MX6PAD(EIM_D19__GPIO3_IO19), WEAK_PULLUP), /* SS1 */

	/* GPIO_KEYS */
#define GP_INSP_GP1		IMX_GPIO_NR(4, 7)
	NEW_PAD_CTRL(MX6PAD(KEY_ROW0__GPIO4_IO07), WEAK_PULLUP),
#define GP_INSP_GP2		IMX_GPIO_NR(4, 8)
	NEW_PAD_CTRL(MX6PAD(KEY_COL1__GPIO4_IO08), WEAK_PULLUP),
#define GP_INSP_GP3		IMX_GPIO_NR(4, 9)
	NEW_PAD_CTRL(MX6PAD(KEY_ROW1__GPIO4_IO09), WEAK_PULLUP),
#define GP_INSP_GP4		IMX_GPIO_NR(4, 10)
	NEW_PAD_CTRL(MX6PAD(KEY_COL2__GPIO4_IO10), WEAK_PULLUP),
#define GP_INSP_GP5		IMX_GPIO_NR(4, 11)
	NEW_PAD_CTRL(MX6PAD(KEY_ROW2__GPIO4_IO11), WEAK_PULLUP),
#define GP_INSP_GP6	IMX_GPIO_NR(1, 2)
	NEW_PAD_CTRL(MX6PAD(GPIO_2__GPIO1_IO02), WEAK_PULLUP),
#define GP_INSP_GP7	IMX_GPIO_NR(1, 4)
	NEW_PAD_CTRL(MX6PAD(GPIO_4__GPIO1_IO04), WEAK_PULLUP),
#define GP_INSP_GP8	IMX_GPIO_NR(1, 7)
	NEW_PAD_CTRL(MX6PAD(GPIO_7__GPIO1_IO07), WEAK_PULLUP),
#define GP_INSP_GP9	IMX_GPIO_NR(1, 8)
	NEW_PAD_CTRL(MX6PAD(GPIO_8__GPIO1_IO08), WEAK_PULLUP),
#define GP_INSP_GP10	IMX_GPIO_NR(1, 9)
	NEW_PAD_CTRL(MX6PAD(GPIO_9__GPIO1_IO09), WEAK_PULLUP),

	/* HDMI */
	NEW_PAD_CTRL(MX6PAD(EIM_A25__HDMI_TX_CEC_LINE), CEC_PAD_CTRL),

	/* I2C2 */
#define GP_J6_I2C_EN		IMX_GPIO_NR(6, 31)
	NEW_PAD_CTRL(MX6PAD(EIM_BCLK__GPIO6_IO31), WEAK_PULLUP_OUTPUT),
#define GP_HDMI_I2C_EN		IMX_GPIO_NR(2, 23)
	NEW_PAD_CTRL(MX6PAD(EIM_CS0__GPIO2_IO23), WEAK_PULLUP_OUTPUT),

	/* I2C3 */
#define GP_TSC2004_IRQ		IMX_GPIO_NR(2, 27)
	NEW_PAD_CTRL(MX6PAD(EIM_LBA__GPIO2_IO27), WEAK_PULLUP),
#define GP_TSC2004_RESET	IMX_GPIO_NR(4, 5)
	NEW_PAD_CTRL(MX6PAD(GPIO_19__GPIO4_IO05), WEAK_PULLUP),


	/* PWM1 */
#define GP_PWM1			IMX_GPIO_NR(1, 21)
	NEW_PAD_CTRL(MX6PAD(SD1_DAT3__GPIO1_IO21), WEAK_PULLDN_OUTPUT),

	/* PWM3 */
#define GP_RGB_BACKLIGHT	IMX_GPIO_NR(1, 17)
	NEW_PAD_CTRL(MX6PAD(SD1_DAT1__GPIO1_IO17), WEAK_PULLDN_OUTPUT),

	/* rtc - i2c1 */
#define GP_RTC_RV4162_IRQ	IMX_GPIO_NR(4, 6)
	NEW_PAD_CTRL(MX6PAD(KEY_COL0__GPIO4_IO06), WEAK_PULLUP),

	/* lvds input on CSI1 */
#ifdef FOR_DL_SOLO
	/* Dualite/Solo doesn't have IPU2 */
	NEW_PAD_CTRL(MX6PAD(EIM_A24__IPU1_CSI1_DATA19), CSI_PAD_CTRL),	/* GPIO2[30] */
	NEW_PAD_CTRL(MX6PAD(EIM_A23__IPU1_CSI1_DATA18), CSI_PAD_CTRL),	/* GPIO6[6] */
	NEW_PAD_CTRL(MX6PAD(EIM_A22__IPU1_CSI1_DATA17), CSI_PAD_CTRL),	/* GPIO2[16] */
	NEW_PAD_CTRL(MX6PAD(EIM_A21__IPU1_CSI1_DATA16), CSI_PAD_CTRL),	/* GPIO2[17] */
	NEW_PAD_CTRL(MX6PAD(EIM_A20__IPU1_CSI1_DATA15), CSI_PAD_CTRL),	/* GPIO2[18] */
	NEW_PAD_CTRL(MX6PAD(EIM_A19__IPU1_CSI1_DATA14), CSI_PAD_CTRL),	/* GPIO2[19] */
	NEW_PAD_CTRL(MX6PAD(EIM_A18__IPU1_CSI1_DATA13), CSI_PAD_CTRL),	/* GPIO2[20] */
	NEW_PAD_CTRL(MX6PAD(EIM_A17__IPU1_CSI1_DATA12), CSI_PAD_CTRL),	/* GPIO2[21] */
	NEW_PAD_CTRL(MX6PAD(EIM_EB0__IPU1_CSI1_DATA11), CSI_PAD_CTRL),	/* GPIO2[28] */
	NEW_PAD_CTRL(MX6PAD(EIM_EB1__IPU1_CSI1_DATA10), CSI_PAD_CTRL),	/* GPIO2[29] */
	NEW_PAD_CTRL(MX6PAD(EIM_A16__IPU1_CSI1_PIXCLK), CSI_PAD_CTRL),	/* GPIO2[22] */
#else
	NEW_PAD_CTRL(MX6PAD(EIM_A24__IPU2_CSI1_DATA19), CSI_PAD_CTRL),	/* GPIO2[30] */
	NEW_PAD_CTRL(MX6PAD(EIM_A23__IPU2_CSI1_DATA18), CSI_PAD_CTRL),	/* GPIO6[6] */
	NEW_PAD_CTRL(MX6PAD(EIM_A22__IPU2_CSI1_DATA17), CSI_PAD_CTRL),	/* GPIO2[16] */
	NEW_PAD_CTRL(MX6PAD(EIM_A21__IPU2_CSI1_DATA16), CSI_PAD_CTRL),	/* GPIO2[17] */
	NEW_PAD_CTRL(MX6PAD(EIM_A20__IPU2_CSI1_DATA15), CSI_PAD_CTRL),	/* GPIO2[18] */
	NEW_PAD_CTRL(MX6PAD(EIM_A19__IPU2_CSI1_DATA14), CSI_PAD_CTRL),	/* GPIO2[19] */
	NEW_PAD_CTRL(MX6PAD(EIM_A18__IPU2_CSI1_DATA13), CSI_PAD_CTRL),	/* GPIO2[20] */
	NEW_PAD_CTRL(MX6PAD(EIM_A17__IPU2_CSI1_DATA12), CSI_PAD_CTRL),	/* GPIO2[21] */
	NEW_PAD_CTRL(MX6PAD(EIM_EB0__IPU2_CSI1_DATA11), CSI_PAD_CTRL),	/* GPIO2[28] */
	NEW_PAD_CTRL(MX6PAD(EIM_EB1__IPU2_CSI1_DATA10), CSI_PAD_CTRL),	/* GPIO2[29] */
	NEW_PAD_CTRL(MX6PAD(EIM_A16__IPU2_CSI1_PIXCLK), CSI_PAD_CTRL),	/* GPIO2[22] */
#endif
#define GP_CAMERA_LOCK		IMX_GPIO_NR(3, 8)			/* low active */
	NEW_PAD_CTRL(MX6PAD(EIM_DA8__GPIO3_IO08), WEAK_PULLUP),
#define GP_CAMERA_POWER_DOWN	IMX_GPIO_NR(3, 9)			/* low active */
	NEW_PAD_CTRL(MX6PAD(EIM_DA9__GPIO3_IO09), WEAK_PULLDN),
#define GP_CAMERA_RX_EN		IMX_GPIO_NR(3, 10)			/* high active */
	NEW_PAD_CTRL(MX6PAD(EIM_DA10__GPIO3_IO10), WEAK_PULLDN),
	NEW_PAD_CTRL(MX6PAD(GPIO_3__CCM_CLKO2), OUTPUT_40OHM),		/* 10 Mhz - 66 MHz */

	/* SGTL5000 */
	NEW_PAD_CTRL(MX6PAD(GPIO_0__CCM_CLKO1), OUTPUT_40OHM),	/* SGTL5000 sys_mclk */
#define GP_SGTL5000_MUTE	IMX_GPIO_NR(1, 29)		/* Low is muted */
	NEW_PAD_CTRL(MX6PAD(ENET_TXD1__GPIO1_IO29), WEAK_PULLDN_OUTPUT),
#define GP_HEADPHONE_DET	IMX_GPIO_NR(7, 8)
	NEW_PAD_CTRL(MX6PAD(SD3_RST__GPIO7_IO08), WEAK_PULLUP),

	/* UART1  */
	NEW_PAD_CTRL(MX6PAD(SD3_DAT7__UART1_TX_DATA), UART_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD3_DAT6__UART1_RX_DATA), UART_PAD_CTRL),

	/* UART2 for debug */
#ifndef CONFIG_SILENT_UART
	NEW_PAD_CTRL(MX6PAD(EIM_D26__UART2_TX_DATA), UART_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(EIM_D27__UART2_RX_DATA), UART_PAD_CTRL),
#else
	NEW_PAD_CTRL(MX6PAD(EIM_D26__GPIO3_IO26), UART_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(EIM_D27__GPIO3_IO27), UART_PAD_CTRL),
#endif
	/* UART3 - Broadcom Bluetooth*/
	NEW_PAD_CTRL(MX6PAD(EIM_D24__UART3_TX_DATA), UART_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(EIM_D25__UART3_RX_DATA), UART_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(EIM_D23__UART3_CTS_B), UART_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(EIM_D31__UART3_RTS_B), UART_PAD_CTRL),

	/* USBH1 */
#define GP_USB_H1_PWR	IMX_GPIO_NR(7, 12)
	NEW_PAD_CTRL(MX6PAD(GPIO_17__GPIO7_IO12), WEAK_PULLDN_OUTPUT),	/* USB Hub Reset for USB2512 4 port hub */
	NEW_PAD_CTRL(MX6PAD(EIM_D30__USB_H1_OC), WEAK_PULLUP),

	/* USBOTG - J3 */
	NEW_PAD_CTRL(MX6PAD(GPIO_1__USB_OTG_ID)	, WEAK_PULLUP),
	NEW_PAD_CTRL(MX6PAD(KEY_COL4__USB_OTG_OC), WEAK_PULLUP),
#define GP_USB_OTG_PWR		IMX_GPIO_NR(3, 22)
	NEW_PAD_CTRL(MX6PAD(EIM_D22__GPIO3_IO22), WEAK_PULLDN_OUTPUT),

	/* USDHC2: TiWi-R2 */
	NEW_PAD_CTRL(MX6PAD(SD2_CLK__SD2_CLK), USDHC_CLK_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD2_CMD__SD2_CMD), USDHC_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD2_DAT0__SD2_DATA0), USDHC_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD2_DAT1__SD2_DATA1), USDHC_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD2_DAT2__SD2_DATA2), USDHC_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD2_DAT3__SD2_DATA3), USDHC_PAD_CTRL),

#define GP_WL_EN		IMX_GPIO_NR(6, 15)
	NEW_PAD_CTRL(MX6PAD(NANDF_CS2__GPIO6_IO15), WEAK_PULLDN),
#define GP_BT_EN		IMX_GPIO_NR(6, 16)
	NEW_PAD_CTRL(MX6PAD(NANDF_CS3__GPIO6_IO16), WEAK_PULLDN),

#define GP_WL_IRQ		IMX_GPIO_NR(6, 11)
	NEW_PAD_CTRL(MX6PAD(NANDF_CS0__GPIO6_IO11), WEAK_PULLDN),
//	NEW_PAD_CTRL(MX6PAD(SD1_CLK__OSC32K_32K_OUT), OUTPUT_40OHM),	/* slow clock */

	/* USDHC3 - sd */
	NEW_PAD_CTRL(MX6PAD(SD3_CLK__SD3_CLK), USDHC_CLK_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD3_CMD__SD3_CMD), USDHC_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD3_DAT0__SD3_DATA0), USDHC_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD3_DAT1__SD3_DATA1), USDHC_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD3_DAT2__SD3_DATA2), USDHC_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD3_DAT3__SD3_DATA3), USDHC_PAD_CTRL),
#define GP_SD3_CD	IMX_GPIO_NR(7, 0)
	NEW_PAD_CTRL(MX6PAD(SD3_DAT5__GPIO7_IO00), NO_PAD_CTRL),
#define GP_SD3_WP	IMX_GPIO_NR(7, 1)
	NEW_PAD_CTRL(MX6PAD(SD3_DAT4__GPIO7_IO01), NO_PAD_CTRL),

	/* USDHC4 - eMMC */
	NEW_PAD_CTRL(MX6PAD(SD4_CLK__SD4_CLK), USDHC_CLK_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD4_CMD__SD4_CMD), USDHC_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD4_DAT0__SD4_DATA0), USDHC_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD4_DAT1__SD4_DATA1), USDHC_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD4_DAT2__SD4_DATA2), USDHC_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD4_DAT3__SD4_DATA3), USDHC_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD4_DAT4__SD4_DATA4), USDHC_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD4_DAT5__SD4_DATA5), USDHC_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD4_DAT6__SD4_DATA6), USDHC_PAD_CTRL),
	NEW_PAD_CTRL(MX6PAD(SD4_DAT7__SD4_DATA7), USDHC_PAD_CTRL),
#define GP_EMMC_RESET	IMX_GPIO_NR(2, 6)
	NEW_PAD_CTRL(MX6PAD(NANDF_D6__GPIO2_IO06), OUTPUT_40OHM),
};

#if defined(CONFIG_VIDEO_IPUV3)
static const iomux_v3_cfg_t MX6NAME(rgb_pads)[] = {
	MX6PAD(DI0_DISP_CLK__IPU1_DI0_DISP_CLK),
	MX6PAD(DI0_PIN15__IPU1_DI0_PIN15),	/* DRDY */
	MX6PAD(DI0_PIN2__IPU1_DI0_PIN02),	/* HSYNC */
	MX6PAD(DI0_PIN3__IPU1_DI0_PIN03),	/* VSYNC */
	MX6PAD(DI0_PIN4__GPIO4_IO20),		/* Contrast */
	MX6PAD(DISP0_DAT0__IPU1_DISP0_DATA00),
	MX6PAD(DISP0_DAT1__IPU1_DISP0_DATA01),
	MX6PAD(DISP0_DAT2__IPU1_DISP0_DATA02),
	MX6PAD(DISP0_DAT3__IPU1_DISP0_DATA03),
	MX6PAD(DISP0_DAT4__IPU1_DISP0_DATA04),
	MX6PAD(DISP0_DAT5__IPU1_DISP0_DATA05),
	MX6PAD(DISP0_DAT6__IPU1_DISP0_DATA06),
	MX6PAD(DISP0_DAT7__IPU1_DISP0_DATA07),
	MX6PAD(DISP0_DAT8__IPU1_DISP0_DATA08),
	MX6PAD(DISP0_DAT9__IPU1_DISP0_DATA09),
	MX6PAD(DISP0_DAT10__IPU1_DISP0_DATA10),
	MX6PAD(DISP0_DAT11__IPU1_DISP0_DATA11),
	MX6PAD(DISP0_DAT12__IPU1_DISP0_DATA12),
	MX6PAD(DISP0_DAT13__IPU1_DISP0_DATA13),
	MX6PAD(DISP0_DAT14__IPU1_DISP0_DATA14),
	MX6PAD(DISP0_DAT15__IPU1_DISP0_DATA15),
	MX6PAD(DISP0_DAT16__IPU1_DISP0_DATA16),
	MX6PAD(DISP0_DAT17__IPU1_DISP0_DATA17),
	MX6PAD(DISP0_DAT18__IPU1_DISP0_DATA18),
	MX6PAD(DISP0_DAT19__IPU1_DISP0_DATA19),
	MX6PAD(DISP0_DAT20__IPU1_DISP0_DATA20),
	MX6PAD(DISP0_DAT21__IPU1_DISP0_DATA21),
	MX6PAD(DISP0_DAT22__IPU1_DISP0_DATA22),
	MX6PAD(DISP0_DAT23__IPU1_DISP0_DATA23),
};
#endif

/*
 *
 */
#define PC I2C_PAD_CTRL

static struct i2c_pads_info MX6NAME(i2c_pad_info)[] = {
{
	/* I2C1, SGTL5000, RTC */
	.scl = {
		.i2c_mode = NEW_PAD_CTRL(MX6PAD(EIM_D21__I2C1_SCL), PC),
		.gpio_mode = NEW_PAD_CTRL(MX6PAD(EIM_D21__GPIO3_IO21), PC),
		.gp = IMX_GPIO_NR(3, 21)
	},
	.sda = {
		.i2c_mode = NEW_PAD_CTRL(MX6PAD(EIM_D28__I2C1_SDA), PC),
		.gpio_mode = NEW_PAD_CTRL(MX6PAD(EIM_D28__GPIO3_IO28), PC),
		.gp = IMX_GPIO_NR(3, 28)
	}
}, {
	/* I2C2 - hdmi */
	.scl = {
		.i2c_mode = NEW_PAD_CTRL(MX6PAD(KEY_COL3__I2C2_SCL), PC),
		.gpio_mode = NEW_PAD_CTRL(MX6PAD(KEY_COL3__GPIO4_IO12), PC),
		.gp = IMX_GPIO_NR(4, 12)
	},
	.sda = {
		.i2c_mode = NEW_PAD_CTRL(MX6PAD(KEY_ROW3__I2C2_SDA), PC),
		.gpio_mode = NEW_PAD_CTRL(MX6PAD(KEY_ROW3__GPIO4_IO13), PC),
		.gp = IMX_GPIO_NR(4, 13)
	}
}, {
	/* I2C3, Charger, PCIe */
	.scl = {
		.i2c_mode = NEW_PAD_CTRL(MX6PAD(GPIO_5__I2C3_SCL), PC),
		.gpio_mode = NEW_PAD_CTRL(MX6PAD(GPIO_5__GPIO1_IO05), PC),
		.gp = IMX_GPIO_NR(1, 5)
	},
	.sda = {
		.i2c_mode = NEW_PAD_CTRL(MX6PAD(GPIO_16__I2C3_SDA), PC),
		.gpio_mode = NEW_PAD_CTRL(MX6PAD(GPIO_16__GPIO7_IO11), PC),
		.gp = IMX_GPIO_NR(7, 11)
	}
}
};
