/*
 * Copyright (C) 2017, Boundary Devices <info@boundarydevices.com>
 *
 * SPDX-License-Identifier:	GPL-2.0+
 */
#define OUTPUT_40OHM		(PAD_CTL_DSE_MED)

#define PAD_CTRL_ENET		(PAD_CTL_PUS_100K_UP |		\
	PAD_CTL_DSE_MED | PAD_CTL_HYS)

#define PAD_CTRL_INPUT	(PAD_CTL_DSE_MED | PAD_CTL_HYS | PAD_CTL_SRE_SLOW)

#define WEAK_PULLDN		(PAD_CTL_PUS_100K_DOWN |	\
	PAD_CTL_DSE_MED | PAD_CTL_HYS | PAD_CTL_SRE_SLOW)

#define WEAK_PULLDN_OUTPUT	(PAD_CTL_PUS_100K_DOWN |	\
	PAD_CTL_DSE_MED | PAD_CTL_SRE_SLOW)

#define WEAK_PULLUP		(PAD_CTL_PUS_100K_UP |		\
	PAD_CTL_DSE_MED | PAD_CTL_HYS | PAD_CTL_SRE_SLOW)

#define WEAK_PULLUP_OUTPUT	(PAD_CTL_PUS_100K_UP |		\
	PAD_CTL_DSE_MED | PAD_CTL_SRE_SLOW)


