/*
 * Copyright (C) 2017, Boundary Devices <info@boundarydevices.com>
 *
 * SPDX-License-Identifier:	GPL-2.0+
 */
#define PAD_CTRL_ENET_MDC	(PAD_CTL_DSE_3P3V_32OHM)
#define PAD_CTRL_ENET_MDIO	(PAD_CTL_DSE_3P3V_32OHM)

#define PAD_CTRL_ENET_RX	(PAD_CTL_DSE_3P3V_49OHM)
#define PAD_CTRL_ENET_RX_DN	(PAD_CTL_PUS_PD100KOHM | PAD_CTRL_ENET_RX)
#define PAD_CTRL_ENET_RX_UP	(PAD_CTL_PUS_PU100KOHM | PAD_CTRL_ENET_RX)

#define PAD_CTRL_ENET_TX	(PAD_CTL_DSE_3P3V_49OHM)

#define WEAK_PULLUP	(PAD_CTL_PUS_PU100KOHM | PAD_CTL_DSE_3P3V_49OHM | \
	PAD_CTL_HYS | PAD_CTL_SRE_SLOW)

#define WEAK_PULLDN_OUTPUT (PAD_CTL_PUS_PD100KOHM | PAD_CTL_DSE_3P3V_49OHM | \
	PAD_CTL_SRE_SLOW)

#define WEAK_PULLUP_OUTPUT (PAD_CTL_PUS_PU100KOHM | PAD_CTL_DSE_3P3V_49OHM | \
	PAD_CTL_SRE_SLOW)

